### ISSUE TITLE
 return value of $payment->getAssetAmount()

### ISSUE THREAD

**Issue by blueskytoday** [zulucrypto/stellar-api#15]
Hi,
thanks for providing this library :-)

I used your sample code to get the payment transactions.
I experienced a confusing behaviour with: $payment->getAssetAmount()

1) $payment->getAssetAmount() delivers an object
2) if I call it together with a string concat like 
''.$payment->getAssetAmount()
I get the XLM-amount

any explanation for that?

Thanks

**Comment by zulucrypto** [comment]
Hi @blueskytoday ,
This behavior is necessary because it's possible to have an amount that's larger than PHP can store with a simple int. 

Instead, assets are wrapped in the `AssetAmount` class which uses a `BigInteger` behind the scenes to make sure large values are stored correctly.

The reason you're seeing things as you expect them when you print them is that `AssetAmount` implements the magic `__toString` method which is called whenever you try to treat an object as a string. See: https://github.com/zulucrypto/stellar-api/blob/110894bf42c8be76fbd9ce686540ce31341cc6ca/src/Model/AssetAmount.php#L74

Check out the other methods on `AssetAmount` if you need to get the asset code or issuer of a custom asset.

**Comment by blueskytoday** [comment]
Ok, thanks for the explanation, still a bit confusing, as this was not clear to me and might surprise others. Wouldn't it be better to have two diff calls, depending if 64-bit Integer is enabled?

**Comment by zulucrypto** [comment]
> Wouldn't it be better to have two diff calls, depending if 64-bit Integer is enabled?

I was hoping to avoid this and keep everything with a single interface, even if it was a bit more complicated to use.

Unfortunately another issue is that PHP doesn't have the concept of an unsigned int64, so even on 64-bit PHP the `BigInteger` class is necessary.

Thanks for opening an issue, I'm sure other people will have the same question!
